// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "JAAB Tech Support",
            "url": "https://fluxrig.org",
            "email": "fluxrig@jaab.tech"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "description": "Returns the current Mixer configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Get Configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.MixerConfig"
                        }
                    }
                }
            }
        },
        "/entities/stats": {
            "get": {
                "description": "Returns cached metrics for a specific entity or all entities.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get Entity Stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/gears": {
            "get": {
                "description": "Returns the manifest catalog: every gear type this build can run, with identity, ports, and config schema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gears"
                ],
                "summary": "List gear manifests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sdk.Manifest"
                            }
                        }
                    }
                }
            }
        },
        "/gears/{type}": {
            "get": {
                "description": "Returns the manifest for a single gear type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gears"
                ],
                "summary": "Get one gear manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Gear type (e.g. io_iso8583)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sdk.Manifest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the operational status of the Mixer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/racks": {
            "get": {
                "description": "Returns a list of all known Racks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registry"
                ],
                "summary": "List Racks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (active, pending, offline)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RackResponse"
                            }
                        }
                    }
                }
            }
        },
        "/racks/{id}/{action}": {
            "post": {
                "description": "Perform actions on Racks (Approve, Suspend, Activate, Remove, Log-Level). Note: This single endpoint handles multiple actions for simplicity in this Alpha version.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registry"
                ],
                "summary": "Rack Actions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Action (approve, suspend, activate)",
                        "name": "action",
                        "in": "path"
                    },
                    {
                        "description": "Approve Request Body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.ApproveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ActionResponse"
                        }
                    }
                }
            }
        },
        "/scenario/active": {
            "get": {
                "description": "Returns the currently active scenario as YAML.",
                "produces": [
                    "application/yaml"
                ],
                "tags": [
                    "scenario"
                ],
                "summary": "Get Active Scenario",
                "responses": {
                    "200": {
                        "description": "Scenario YAML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scenario/import": {
            "post": {
                "description": "Upload a YAML scenario definition to update the topology.",
                "consumes": [
                    "application/x-yaml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scenario"
                ],
                "summary": "Import Scenario",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Validate without applying",
                        "name": "dry_run",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Immediately activate after import",
                        "name": "activate",
                        "in": "query"
                    },
                    {
                        "description": "Scenario YAML",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registry.Scenario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScenarioImportResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/{type}": {
            "get": {
                "description": "Query Logs or Metrics from DuckDB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Query Telemetry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of telemetry (logs, metrics)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by Entity Name",
                        "name": "entity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Level (logs only)",
                        "name": "min_level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (e.g. 1h, 2023-01-01T00:00:00Z)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max records (default 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/topology/list": {
            "get": {
                "description": "Returns the projected topology with rack and gear details.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "List Topology",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/topology/status": {
            "get": {
                "description": "Returns synchronization status of the fleet",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "Topology Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TopologyStatusResponse"
                        }
                    }
                }
            }
        },
        "/wasm/catalog": {
            "get": {
                "description": "Returns the catalog of trusted and available Wasm modules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wasm"
                ],
                "summary": "List Wasm Catalog",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/wasm/import": {
            "post": {
                "description": "Securely imports, validates, and distributes a Wasm payload",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wasm"
                ],
                "summary": "Import Wasm Module",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Allow unsigned modules",
                        "name": "allow_unsigned",
                        "in": "query"
                    },
                    {
                        "description": "Wasm binary payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ActionResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the rack (for import/approve).",
                    "type": "string",
                    "example": "rack-01"
                },
                "status": {
                    "description": "Status of the action.",
                    "type": "string",
                    "example": "activated"
                }
            }
        },
        "api.ApproveRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name to assign to the rack (optional, defaults to current).",
                    "type": "string",
                    "example": "rack-prod-01"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "entity_id": {
                    "description": "EntityID is the unique fluxEntityID of this Mixer.",
                    "type": "string",
                    "example": "019de49b-0000-7000-8000-000000000000"
                },
                "machine_id": {
                    "description": "MachineID is the persistent machine ID.",
                    "type": "string",
                    "example": "019de49b-0000-7000-8000-000000000000"
                },
                "status": {
                    "description": "Status of the service (e.g. \"ok\").",
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "description": "Version of the service.",
                    "type": "string",
                    "example": "0.1.0"
                }
            }
        },
        "api.RackResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "Config (Runtime).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.RackConfig"
                        }
                    ]
                },
                "first_seen": {
                    "description": "FirstSeen timestamp.",
                    "type": "string",
                    "example": "2023-10-26T10:00:00Z"
                },
                "id": {
                    "description": "ID is the entity ID of the rack.",
                    "type": "string",
                    "example": "45612378"
                },
                "ip": {
                    "description": "IP address of the rack agent.",
                    "type": "string",
                    "example": "192.168.1.50"
                },
                "last_seen": {
                    "description": "LastSeen timestamp.",
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "machine_id": {
                    "description": "MachineID is the physical machine ID.",
                    "type": "string",
                    "example": "019de49b-0000-7000-8000-000000000000"
                },
                "name": {
                    "description": "Name of the rack.",
                    "type": "string",
                    "example": "rack-01"
                },
                "port": {
                    "description": "Port number of the rack agent.",
                    "type": "integer",
                    "example": 4222
                },
                "stats": {
                    "description": "Stats (Transient/Snapshot).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.RackStats"
                        }
                    ]
                },
                "status": {
                    "description": "Status of the rack (active, inactive, pending).",
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "api.RackStats": {
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "description": "CPU usage percentage.",
                    "type": "number",
                    "example": 12.5
                },
                "load_avg": {
                    "description": "Load average (1m).",
                    "type": "number",
                    "example": 0.5
                },
                "mem_usage": {
                    "description": "Memory usage percentage.",
                    "type": "number",
                    "example": 45.2
                },
                "uptime": {
                    "description": "Uptime in seconds.",
                    "type": "integer",
                    "example": 3600
                }
            }
        },
        "api.ScenarioImportResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the imported scenario.",
                    "type": "string",
                    "example": "payment-switch-v1"
                },
                "status": {
                    "description": "Status of the import.",
                    "type": "string",
                    "example": "imported_and_activated"
                }
            }
        },
        "api.TopologyStatusResponse": {
            "type": "object",
            "properties": {
                "active_scenario": {
                    "description": "ActiveScenario is the name of the currently active scenario.",
                    "type": "string",
                    "example": "Getting Started"
                },
                "active_ver": {
                    "description": "ActiveVer is the currently active scenario version.",
                    "type": "string",
                    "example": "v1.2.3"
                },
                "racks_total": {
                    "description": "RacksTotal is the total number of registered racks.",
                    "type": "integer",
                    "example": 50
                },
                "sync_status": {
                    "description": "SyncStatus indicates global sync state.",
                    "type": "string",
                    "example": "synchronized"
                }
            }
        },
        "config.ApiConfig": {
            "type": "object",
            "properties": {
                "port": {
                    "description": "Port to listen on.",
                    "type": "integer",
                    "example": 8090
                },
                "readHeaderTimeout": {
                    "description": "ReadHeaderTimeout for the HTTP server.",
                    "type": "string",
                    "example": "3s"
                },
                "tlscertFile": {
                    "description": "TLSCertFile path to server certificate.",
                    "type": "string",
                    "example": "server.crt"
                },
                "tlskeyFile": {
                    "description": "TLSKeyFile path to server key.",
                    "type": "string",
                    "example": "server.key"
                }
            }
        },
        "config.BaseConfig": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "node-01"
                },
                "stateDir": {
                    "type": "string",
                    "example": "./data"
                },
                "stateFile": {
                    "type": "string",
                    "example": "rack.flux"
                }
            }
        },
        "config.EmbeddedConfig": {
            "type": "object",
            "properties": {
                "flushInterval": {
                    "description": "FlushInterval for the embedded stack.",
                    "type": "string",
                    "example": "5s"
                },
                "retentionDays": {
                    "description": "RetentionDays for local parquet files.",
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "config.EnrollmentConfig": {
            "type": "object",
            "properties": {
                "autoAdopt": {
                    "description": "AutoAdopt, if true, will automatically mark newly enrolled Racks as 'active'.\nIf false (default), new Racks start as 'pending'.",
                    "type": "boolean",
                    "example": false
                },
                "bootstrapSecret": {
                    "description": "BootstrapSecret is the shared secret used for zero-config enrollment and identity adoption.\nDefaults to 'fluxrig' if not specified.",
                    "type": "string",
                    "example": "fluxrig"
                },
                "pushDelay": {
                    "description": "PushDelay is the time to wait before pushing state to a newly enrolled Rack.",
                    "type": "string",
                    "example": "1s"
                }
            }
        },
        "config.IngestConfig": {
            "type": "object",
            "properties": {
                "bufferSize": {
                    "description": "BufferSize is the internal channel buffer size (deprecated).",
                    "type": "integer",
                    "example": 1024
                },
                "flushInterval": {
                    "description": "FlushInterval determines how often to flush data to Parquet.",
                    "type": "string",
                    "example": "5s"
                }
            }
        },
        "config.LoggingConfig": {
            "type": "object",
            "properties": {
                "compress": {
                    "type": "boolean",
                    "example": true
                },
                "debug": {
                    "description": "Hard-override for debug level",
                    "type": "boolean"
                },
                "filename": {
                    "type": "string",
                    "example": "logs/fluxrig.log"
                },
                "level": {
                    "type": "string",
                    "example": "info"
                },
                "maxBackups": {
                    "type": "integer",
                    "example": 7
                },
                "maxSizeMB": {
                    "type": "integer",
                    "example": 100
                },
                "throttling": {
                    "$ref": "#/definitions/config.ThrottlingConfig"
                },
                "trace": {
                    "description": "Hard-override for trace level",
                    "type": "boolean"
                }
            }
        },
        "config.MetricsConfig": {
            "type": "object",
            "properties": {
                "bentoEnabled": {
                    "type": "boolean"
                },
                "hostEnabled": {
                    "type": "boolean"
                },
                "runtimeEnabled": {
                    "type": "boolean"
                }
            }
        },
        "config.MixerConfig": {
            "type": "object",
            "properties": {
                "api": {
                    "$ref": "#/definitions/config.ApiConfig"
                },
                "base": {
                    "$ref": "#/definitions/config.BaseConfig"
                },
                "enrollment": {
                    "$ref": "#/definitions/config.EnrollmentConfig"
                },
                "ingest": {
                    "$ref": "#/definitions/config.IngestConfig"
                },
                "logging": {
                    "$ref": "#/definitions/config.LoggingConfig"
                },
                "mixer": {
                    "$ref": "#/definitions/config.MixerSettings"
                },
                "observability": {
                    "$ref": "#/definitions/config.ObservabilityConfig"
                },
                "snake": {
                    "$ref": "#/definitions/config.SnakeConfig"
                },
                "store": {
                    "$ref": "#/definitions/config.StoreConfig"
                },
                "telemetry": {
                    "$ref": "#/definitions/config.TelemetryConfig"
                },
                "wasm": {
                    "$ref": "#/definitions/config.WasmConfig"
                }
            }
        },
        "config.MixerSettings": {
            "type": "object",
            "properties": {
                "maxHops": {
                    "description": "Message Limits",
                    "type": "integer"
                },
                "maxPayloadSize": {
                    "type": "integer"
                },
                "scenarioWaitTimeout": {
                    "description": "ScenarioWaitTimeout is the time to wait for a rack to register when activating a scenario.",
                    "type": "string",
                    "example": "15s"
                },
                "startupScenario": {
                    "description": "StartupScenario reference to the scenario to load on startup.",
                    "type": "string"
                }
            }
        },
        "config.ObservabilityConfig": {
            "type": "object",
            "properties": {
                "embedded": {
                    "description": "Embedded configures the local embedded stack.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.EmbeddedConfig"
                        }
                    ]
                },
                "enabled": {
                    "description": "Enabled master switch for observability features.",
                    "type": "boolean",
                    "example": true
                },
                "tier": {
                    "description": "Tier selects the backend (embedded or standard).",
                    "type": "string",
                    "example": "embedded"
                }
            }
        },
        "config.RackConfig": {
            "type": "object",
            "properties": {
                "base": {
                    "$ref": "#/definitions/config.BaseConfig"
                },
                "logging": {
                    "$ref": "#/definitions/config.LoggingConfig"
                },
                "rack": {
                    "$ref": "#/definitions/config.RackSettings"
                },
                "snake": {
                    "$ref": "#/definitions/config.SnakeConfig"
                },
                "store": {
                    "$ref": "#/definitions/config.StoreConfig"
                },
                "telemetry": {
                    "$ref": "#/definitions/config.TelemetryConfig"
                }
            }
        },
        "config.RackSettings": {
            "type": "object",
            "properties": {
                "cleanupTimeout": {
                    "type": "string"
                },
                "convergenceTimeout": {
                    "type": "string"
                },
                "drainTimeout": {
                    "description": "DrainTimeout bounds a graceful stop (SIGTERM or shutdown command). It\nmust exceed the largest gear ticket TTL so in-flight work can complete\nor time out before the process exits. Default 35s (\u003e a 30s switch TTL).",
                    "type": "string"
                },
                "enrollmentInterval": {
                    "type": "string"
                },
                "enrollmentTimeout": {
                    "type": "string"
                },
                "handshakeInterval": {
                    "type": "string"
                },
                "heartbeatInterval": {
                    "type": "string"
                },
                "ip": {
                    "type": "string",
                    "example": "10.0.0.5"
                },
                "machineID": {
                    "description": "Runtime only: set via Passport or Mixer assignment",
                    "type": "string"
                },
                "maxHops": {
                    "type": "integer"
                },
                "maxPayloadSize": {
                    "type": "integer"
                },
                "namePrefix": {
                    "type": "string"
                }
            }
        },
        "config.SnakeConfig": {
            "type": "object",
            "properties": {
                "connectTimeout": {
                    "type": "string",
                    "example": "10s"
                },
                "convergenceDelay": {
                    "type": "string",
                    "example": "100ms"
                },
                "domain": {
                    "type": "string",
                    "example": "flux"
                },
                "inactiveThreshold": {
                    "type": "string",
                    "example": "30s"
                },
                "insecureSkipVerify": {
                    "type": "boolean"
                },
                "operationTimeout": {
                    "type": "string",
                    "example": "5s"
                },
                "port": {
                    "type": "integer",
                    "example": 4222
                },
                "reconnectWait": {
                    "type": "string",
                    "example": "1s"
                },
                "rootCAFile": {
                    "type": "string"
                },
                "streamName": {
                    "type": "string",
                    "example": "flux-msg"
                },
                "streamSubjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subscriptionRetryAttempts": {
                    "type": "integer",
                    "example": 5
                },
                "subscriptionRetryWait": {
                    "type": "string",
                    "example": "200ms"
                },
                "tlscertFile": {
                    "type": "string"
                },
                "tlskeyFile": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "example": "nats://localhost:4222"
                }
            }
        },
        "config.StoreConfig": {
            "type": "object",
            "properties": {
                "clusterKeyFile": {
                    "type": "string",
                    "example": "cluster.key"
                },
                "databaseFile": {
                    "type": "string",
                    "example": "flux.duckdb"
                },
                "dir": {
                    "type": "string",
                    "example": "./data"
                },
                "walmaxSizeMB": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "config.TelemetryConfig": {
            "type": "object",
            "properties": {
                "baseSubject": {
                    "type": "string"
                },
                "batchInterval": {
                    "type": "string"
                },
                "disabled": {
                    "description": "Master switch to disable all telemetry",
                    "type": "boolean"
                },
                "maxBatchSize": {
                    "type": "integer"
                },
                "metrics": {
                    "$ref": "#/definitions/config.MetricsConfig"
                },
                "serviceName": {
                    "type": "string"
                },
                "streamName": {
                    "type": "string"
                },
                "streamSubjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "config.ThrottlingConfig": {
            "type": "object",
            "properties": {
                "burst": {
                    "type": "integer",
                    "example": 50
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "rate": {
                    "type": "number",
                    "example": 500
                }
            }
        },
        "config.WasmConfig": {
            "type": "object",
            "properties": {
                "catalogDir": {
                    "type": "string",
                    "example": "./data/wasm"
                },
                "trustedKeysDir": {
                    "type": "string",
                    "example": "./data/wasm/keys"
                }
            }
        },
        "registry.GearSpec": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "deploy": {
                    "description": "string (Group/Rack) or map",
                    "type": "string",
                    "example": "rack-group-1"
                },
                "doc": {
                    "type": "string",
                    "example": "Primary Ingress"
                },
                "id": {
                    "description": "Assigned by Registry/Mixer",
                    "type": "string",
                    "example": "100"
                },
                "name": {
                    "type": "string",
                    "example": "iso8583-in"
                },
                "ports": {
                    "description": "Assigned by Mixer",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string",
                    "example": "iso8583-server"
                }
            }
        },
        "registry.LabelMatch": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "registry.RackTarget": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "defaults": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "group": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "match": {
                    "$ref": "#/definitions/registry.LabelMatch"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "registry.Scenario": {
            "type": "object",
            "properties": {
                "gears": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.GearSpec"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/registry.ScenarioMeta"
                },
                "racks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.RackTarget"
                    }
                },
                "wires": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.WireSpec"
                    }
                }
            }
        },
        "registry.ScenarioMeta": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "payment-switch"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "registry.WireSpec": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "example": "iso8583-in.out"
                },
                "id": {
                    "description": "Assigned by Registry/Mixer",
                    "type": "string"
                },
                "to": {
                    "type": "string",
                    "example": "router.in"
                }
            }
        },
        "sdk.GearCategory": {
            "type": "string",
            "enum": [
                "io",
                "codec",
                "logic",
                "observability"
            ],
            "x-enum-varnames": [
                "CategoryIO",
                "CategoryCodec",
                "CategoryLogic",
                "CategoryObservability"
            ]
        },
        "sdk.GearStatus": {
            "type": "string",
            "enum": [
                "stable",
                "roadmap"
            ],
            "x-enum-varnames": [
                "StatusStable",
                "StatusRoadmap"
            ]
        },
        "sdk.Manifest": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category groups the gear for classification and styling.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sdk.GearCategory"
                        }
                    ]
                },
                "config_schema": {
                    "description": "ConfigSchema is the gear's configuration contract as a JSON Schema\n(draft-07) document. Empty means the gear takes no configuration.",
                    "type": "string"
                },
                "doc_slug": {
                    "description": "DocSlug is the reference-page slug on the public docs site; the full\nURL is derived. Empty means no dedicated page.",
                    "type": "string"
                },
                "ports": {
                    "description": "Ports are the input/output ports the gear declares.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sdk.Port"
                    }
                },
                "status": {
                    "description": "Status is the maturity of the gear type.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sdk.GearStatus"
                        }
                    ]
                },
                "summary": {
                    "description": "Summary is a one-line description.",
                    "type": "string"
                },
                "terminus": {
                    "description": "Terminus tells the runtime binding walk how to treat this gear when it\nis the endpoint of a wire path. The zero value (TerminusTransparent)\nmeans a single-path pass-through, e.g. a codec.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sdk.TerminusKind"
                        }
                    ]
                },
                "type": {
                    "description": "Type is the gear type string, matching factory registration\n(e.g. \"io_iso8583\").",
                    "type": "string"
                }
            }
        },
        "sdk.Port": {
            "type": "object",
            "properties": {
                "dir": {
                    "description": "Dir is the port direction.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sdk.PortDir"
                        }
                    ]
                },
                "dynamic": {
                    "description": "Dynamic is true when instances are user-named and Name is a pattern\n(e.g. \"out_\u003cname\u003e\", \"out_response_\u003corigin\u003e\").",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is the port name. It may be a concrete name (\"in\", \"out\",\n\"error\") or a pattern for user-named ports (\"out_\u003cname\u003e\") when Dynamic\nis true. Port names never contain dots (dots separate rack/gear/port in a\nwire endpoint); roles use underscores.",
                    "type": "string"
                },
                "role": {
                    "description": "Role is a free-form role tag for tooling and documentation:\n\"request\"/\"reply\"/\"response\"/\"error\" on a switch, \"ingress\"/\"egress\"\non an I/O gear (relative to the mesh), or \"message\" on a plain\ntransform/logic data port.",
                    "type": "string"
                },
                "summary": {
                    "description": "Summary is a one-line description of the port.",
                    "type": "string"
                }
            }
        },
        "sdk.PortDir": {
            "type": "string",
            "enum": [
                "input",
                "output"
            ],
            "x-enum-varnames": [
                "PortIn",
                "PortOut"
            ]
        },
        "sdk.TerminusKind": {
            "type": "string",
            "enum": [
                "transparent",
                "io",
                "opaque"
            ],
            "x-enum-varnames": [
                "TerminusTransparent",
                "TerminusIO",
                "TerminusOpaque"
            ]
        }
    },
    "externalDocs": {
        "description": "fluxrig Architecture Guide",
        "url": "https://fluxrig.org/docs/architecture"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0-dev",
	Host:             "localhost:8090",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "fluxrig Mixer API",
	Description:      "Control Plane API for fluxrig Orchestration. The Mixer acts as the brain of the fleet, managing Rack enrollment, Scenario deployment, and global Telemetry aggregation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
