// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "JAAB Tech Support",
            "url": "https://fluxrig.org",
            "email": "fluxrig@jaab.tech"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "description": "Returns the current Mixer configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Get Configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.MixerConfig"
                        }
                    }
                }
            }
        },
        "/entities/stats": {
            "get": {
                "description": "Returns cached metrics for a specific entity or all entities.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get Entity Stats",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the operational status of the Mixer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "core"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/racks": {
            "get": {
                "description": "Returns a list of all known Racks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registry"
                ],
                "summary": "List Racks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (active, pending, offline)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.RackResponse"
                            }
                        }
                    }
                }
            }
        },
        "/racks/{id}/{action}": {
            "post": {
                "description": "Perform actions on Racks (Approve, Suspend, Activate, Remove, Log-Level). Note: This single endpoint handles multiple actions for simplicity in this Alpha version.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "registry"
                ],
                "summary": "Rack Actions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Action (approve, suspend, activate)",
                        "name": "action",
                        "in": "path"
                    },
                    {
                        "description": "Approve Request Body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.ApproveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ActionResponse"
                        }
                    }
                }
            }
        },
        "/scenario/active": {
            "get": {
                "description": "Returns the currently active scenario as YAML.",
                "produces": [
                    "application/yaml"
                ],
                "tags": [
                    "scenario"
                ],
                "summary": "Get Active Scenario",
                "responses": {
                    "200": {
                        "description": "Scenario YAML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scenario/import": {
            "post": {
                "description": "Upload a YAML scenario definition to update the topology.",
                "consumes": [
                    "application/x-yaml"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scenario"
                ],
                "summary": "Import Scenario",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Validate without applying",
                        "name": "dry_run",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Immediately activate after import",
                        "name": "activate",
                        "in": "query"
                    },
                    {
                        "description": "Scenario YAML",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registry.Scenario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScenarioImportResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/{type}": {
            "get": {
                "description": "Query Logs or Metrics from DuckDB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Query Telemetry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of telemetry (logs, metrics)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by Entity Name",
                        "name": "entity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Level (logs only)",
                        "name": "min_level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (e.g. 1h, 2023-01-01T00:00:00Z)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max records (default 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/topology/list": {
            "get": {
                "description": "Returns the projected topology with rack and gear details.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "List Topology",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/topology/status": {
            "get": {
                "description": "Returns synchronization status of the fleet",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "topology"
                ],
                "summary": "Topology Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TopologyStatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ActionResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the rack (for import/approve).",
                    "type": "string",
                    "example": "rack-01"
                },
                "status": {
                    "description": "Status of the action.",
                    "type": "string",
                    "example": "activated"
                }
            }
        },
        "api.ApproveRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name to assign to the rack (optional, defaults to current).",
                    "type": "string",
                    "example": "rack-prod-01"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status of the service (e.g. \"ok\").",
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "description": "Version of the service.",
                    "type": "string",
                    "example": "0.1.0"
                }
            }
        },
        "api.RackResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "Config (Runtime).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.RackConfig"
                        }
                    ]
                },
                "first_seen": {
                    "description": "FirstSeen timestamp.",
                    "type": "string",
                    "example": "2023-10-26T10:00:00Z"
                },
                "id": {
                    "description": "ID is the entity ID of the rack.",
                    "type": "integer",
                    "example": 45612378
                },
                "ip": {
                    "description": "IP address of the rack agent.",
                    "type": "string",
                    "example": "192.168.1.50"
                },
                "last_seen": {
                    "description": "LastSeen timestamp.",
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "machine_id": {
                    "description": "MachineID is the physical machine ID.",
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "description": "Name of the rack.",
                    "type": "string",
                    "example": "rack-01"
                },
                "port": {
                    "description": "Port number of the rack agent.",
                    "type": "integer",
                    "example": 4222
                },
                "stats": {
                    "description": "Stats (Transient/Snapshot).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.RackStats"
                        }
                    ]
                },
                "status": {
                    "description": "Status of the rack (active, inactive, pending).",
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "api.RackStats": {
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "description": "CPU usage percentage.",
                    "type": "number",
                    "example": 12.5
                },
                "load_avg": {
                    "description": "Load average (1m).",
                    "type": "number",
                    "example": 0.5
                },
                "mem_usage": {
                    "description": "Memory usage percentage.",
                    "type": "number",
                    "example": 45.2
                },
                "uptime": {
                    "description": "Uptime in seconds.",
                    "type": "integer",
                    "example": 3600
                }
            }
        },
        "api.ScenarioImportResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the imported scenario.",
                    "type": "string",
                    "example": "payment-switch-v1"
                },
                "status": {
                    "description": "Status of the import.",
                    "type": "string",
                    "example": "imported_and_activated"
                }
            }
        },
        "api.TopologyStatusResponse": {
            "type": "object",
            "properties": {
                "active_ver": {
                    "description": "ActiveVer is the currently active scenario version.",
                    "type": "string",
                    "example": "v1.2.3"
                },
                "racks_total": {
                    "description": "RacksTotal is the total number of registered racks.",
                    "type": "integer",
                    "example": 50
                },
                "sync_status": {
                    "description": "SyncStatus indicates global sync state.",
                    "type": "string",
                    "example": "synchronized"
                }
            }
        },
        "config.ApiConfig": {
            "type": "object",
            "properties": {
                "port": {
                    "description": "Port to listen on.",
                    "type": "integer",
                    "example": 8090
                },
                "readHeaderTimeout": {
                    "description": "ReadHeaderTimeout for the HTTP server.",
                    "type": "string",
                    "example": "3s"
                },
                "tlscertFile": {
                    "description": "TLSCertFile path to server certificate.",
                    "type": "string",
                    "example": "server.crt"
                },
                "tlskeyFile": {
                    "description": "TLSKeyFile path to server key.",
                    "type": "string",
                    "example": "server.key"
                }
            }
        },
        "config.BusConfig": {
            "type": "object",
            "properties": {
                "connectTimeout": {
                    "type": "string"
                },
                "convergenceDelay": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "insecureSkipVerify": {
                    "type": "boolean"
                },
                "operationTimeout": {
                    "type": "string"
                },
                "reconnectWait": {
                    "type": "string"
                },
                "rootCA": {
                    "type": "string"
                },
                "streamName": {
                    "type": "string"
                },
                "subscriptionRetryAttempts": {
                    "type": "integer"
                },
                "subscriptionRetryWait": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "config.EmbeddedConfig": {
            "type": "object",
            "properties": {
                "flushInterval": {
                    "description": "FlushInterval for the embedded stack.",
                    "type": "string",
                    "example": "5s"
                },
                "retentionDays": {
                    "description": "RetentionDays for local parquet files.",
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "config.EnrollmentConfig": {
            "type": "object",
            "properties": {
                "autoAdopt": {
                    "description": "AutoAdopt, if true, will automatically mark newly enrolled Racks as 'active'.\nIf false (default), new Racks start as 'pending'.",
                    "type": "boolean",
                    "example": false
                },
                "pushDelay": {
                    "description": "PushDelay is the time to wait before pushing state to a newly enrolled Rack.",
                    "type": "string",
                    "example": "1s"
                }
            }
        },
        "config.IngestConfig": {
            "type": "object",
            "properties": {
                "bufferSize": {
                    "description": "BufferSize is the internal channel buffer size (deprecated).",
                    "type": "integer",
                    "example": 1024
                },
                "flushInterval": {
                    "description": "FlushInterval determines how often to flush data to Parquet.",
                    "type": "string",
                    "example": "5s"
                }
            }
        },
        "config.LoggingConfig": {
            "type": "object",
            "properties": {
                "compress": {
                    "type": "boolean"
                },
                "filename": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "maxBackups": {
                    "type": "integer"
                },
                "maxSizeMB": {
                    "type": "integer"
                },
                "throttling": {
                    "$ref": "#/definitions/config.ThrottlingConfig"
                }
            }
        },
        "config.MetricsConfig": {
            "type": "object",
            "properties": {
                "bentoEnabled": {
                    "type": "boolean"
                },
                "hostEnabled": {
                    "type": "boolean"
                },
                "runtimeEnabled": {
                    "type": "boolean"
                }
            }
        },
        "config.MixerConfig": {
            "type": "object",
            "properties": {
                "api": {
                    "$ref": "#/definitions/config.ApiConfig"
                },
                "enrollment": {
                    "$ref": "#/definitions/config.EnrollmentConfig"
                },
                "ingest": {
                    "$ref": "#/definitions/config.IngestConfig"
                },
                "logging": {
                    "$ref": "#/definitions/config.LoggingConfig"
                },
                "mixer": {
                    "$ref": "#/definitions/config.MixerSettings"
                },
                "observability": {
                    "$ref": "#/definitions/config.ObservabilityConfig"
                },
                "snake": {
                    "$ref": "#/definitions/config.SnakeConfig"
                },
                "store": {
                    "$ref": "#/definitions/config.StoreConfig"
                },
                "telemetry": {
                    "$ref": "#/definitions/config.TelemetryConfig"
                }
            }
        },
        "config.MixerSettings": {
            "type": "object",
            "properties": {
                "machineID": {
                    "description": "MachineID is the unique physical ID of the Mixer machine.",
                    "type": "integer",
                    "example": 1
                },
                "mixerName": {
                    "description": "MixerName is the human-readable name of the Mixer.",
                    "type": "string",
                    "example": "mixer-01"
                },
                "startupScenario": {
                    "description": "StartupScenario reference to the scenario to load on startup.\nAccepts: file path (\"/path/to/file.yaml\"), URN (\"payment-flow:v1.0.0\"),\nor empty string (resume last active scenario).",
                    "type": "string"
                }
            }
        },
        "config.ObservabilityConfig": {
            "type": "object",
            "properties": {
                "embedded": {
                    "description": "Embedded configures the local embedded stack.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/config.EmbeddedConfig"
                        }
                    ]
                },
                "enabled": {
                    "description": "Enabled master switch for observability features.",
                    "type": "boolean",
                    "example": true
                },
                "tier": {
                    "description": "Tier selects the backend (embedded or standard).",
                    "type": "string",
                    "example": "embedded"
                }
            }
        },
        "config.RackConfig": {
            "type": "object",
            "properties": {
                "logging": {
                    "$ref": "#/definitions/config.LoggingConfig"
                },
                "rack": {
                    "$ref": "#/definitions/config.RackSettings"
                },
                "store": {
                    "$ref": "#/definitions/config.StoreConfig"
                },
                "telemetry": {
                    "$ref": "#/definitions/config.TelemetryConfig"
                }
            }
        },
        "config.RackSettings": {
            "type": "object",
            "properties": {
                "bus": {
                    "$ref": "#/definitions/config.BusConfig"
                },
                "cleanupTimeout": {
                    "type": "string"
                },
                "convergenceTimeout": {
                    "type": "string"
                },
                "enrollmentTimeout": {
                    "type": "string"
                },
                "handshakeInterval": {
                    "type": "string"
                },
                "heartbeatInterval": {
                    "type": "string"
                },
                "machineID": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namePrefix": {
                    "type": "string"
                }
            }
        },
        "config.SnakeConfig": {
            "type": "object",
            "properties": {
                "businessStreamMaxAge": {
                    "description": "BusinessStreamMaxAge retention policy.",
                    "type": "string",
                    "example": "720h"
                },
                "clusterName": {
                    "description": "ClusterName for NATS clustering.",
                    "type": "string",
                    "example": "flux"
                },
                "durable": {
                    "description": "Durable toggles file-based storage.",
                    "type": "boolean",
                    "example": false
                },
                "operationTimeout": {
                    "description": "OperationTimeout for NATS requests.",
                    "type": "string",
                    "example": "5s"
                },
                "port": {
                    "description": "Port for NATS client connections.",
                    "type": "integer",
                    "example": 4222
                },
                "rootCAFile": {
                    "description": "RootCAFile for client connections (loopback).",
                    "type": "string"
                },
                "streamName": {
                    "description": "StreamName for the primary business stream.",
                    "type": "string",
                    "example": "flux-msg"
                },
                "streamSubjects": {
                    "description": "StreamSubjects to bind to the stream.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "flux.msg.\u003e"
                    ]
                },
                "telemetryStreamMaxAge": {
                    "description": "TelemetryStreamMaxAge retention policy.",
                    "type": "string",
                    "example": "24h"
                },
                "tlscertFile": {
                    "description": "TLSCertFile for server-side TLS.",
                    "type": "string"
                },
                "tlskeyFile": {
                    "description": "TLSKeyFile for server-side TLS.",
                    "type": "string"
                },
                "url": {
                    "description": "URL for internal connections.",
                    "type": "string",
                    "example": "nats://localhost:4222"
                }
            }
        },
        "config.StoreConfig": {
            "type": "object",
            "properties": {
                "clusterKeyFile": {
                    "type": "string"
                },
                "databaseFile": {
                    "type": "string"
                },
                "dir": {
                    "type": "string"
                },
                "stateFile": {
                    "type": "string"
                },
                "walmaxSizeMB": {
                    "type": "integer"
                }
            }
        },
        "config.TelemetryConfig": {
            "type": "object",
            "properties": {
                "baseSubject": {
                    "type": "string"
                },
                "batchInterval": {
                    "type": "string"
                },
                "maxBatchSize": {
                    "type": "integer"
                },
                "metrics": {
                    "$ref": "#/definitions/config.MetricsConfig"
                },
                "serviceName": {
                    "type": "string"
                }
            }
        },
        "config.ThrottlingConfig": {
            "type": "object",
            "properties": {
                "burst": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "rate": {
                    "type": "number"
                }
            }
        },
        "registry.GearSpec": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "deploy": {
                    "description": "string (Group/Rack) or map",
                    "type": "string",
                    "example": "rack-group-1"
                },
                "doc": {
                    "type": "string",
                    "example": "Primary Ingress"
                },
                "id": {
                    "description": "Assigned by Registry/Mixer",
                    "type": "integer",
                    "example": 100
                },
                "name": {
                    "type": "string",
                    "example": "iso8583-in"
                },
                "ports": {
                    "description": "Assigned by Mixer",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "type": {
                    "type": "string",
                    "example": "iso8583-server"
                }
            }
        },
        "registry.LabelMatch": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "registry.RackTarget": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "defaults": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "group": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "match": {
                    "$ref": "#/definitions/registry.LabelMatch"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "registry.Scenario": {
            "type": "object",
            "properties": {
                "gears": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.GearSpec"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/registry.ScenarioMeta"
                },
                "racks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.RackTarget"
                    }
                },
                "wires": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registry.WireSpec"
                    }
                }
            }
        },
        "registry.ScenarioMeta": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "payment-switch"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "registry.WireSpec": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "example": "iso8583-in.out"
                },
                "id": {
                    "description": "Assigned by Registry/Mixer",
                    "type": "integer"
                },
                "to": {
                    "type": "string",
                    "example": "router.in"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.4.5-dev",
	Host:             "localhost:8090",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "FluxRig Mixer API",
	Description:      "Control Plane API for FluxRig Orchestration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
