# Copyright 2025 JAAB Tech SAS, Uruguay
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/jaab-tech/fluxrig

linters:
  enable:
    - unused
    - bodyclose
    - noctx
    - rowserrcheck
    - gosec
    - gofmt
  disable:
    - depguard
    - gochecknoglobals
    - gochecknoinits

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
