
import struct
from iso8583.specs import default_ascii
import iso8583

# Test LE Encoding
data = {"t": "0800", "7": "0101000000", "11": "000001", "70": "001"}
try:
    # Attempt to encode via library
    # Note: pyiso8583 doesn't seem to have a global 'endian' switch for the whole packet hierarchy easily?
    # It relies on specs.
    # Let's check how we send it in iso8583_tool.py:
    # frame = encode_with_length_prefix(payload, header_bytes, endian)
    # The payload itself is encoded by: raw_bytes, _ = iso8583.encode(decoded_msg, spec)
    # The library encodes fields.
    
    raw, _ = iso8583.encode(data, default_ascii)
    print(f"Encoded (ASCII): {raw}")
    
    # In LE mode, we just wrap it with Little Endian Length Header
    # frame = struct.pack("<H", len(raw)) + raw
    
    # If the Rack expects LE data... wait.
    # ISO8583 standard is usually Big Endian for data fields (e.g. Length Prefix of LVAR).
    # Does 'fluxrig.toml' endianness setting affect the *field content* or just the *frame length prefix*?
    
    # Let's check iso8583_tool.py again.
    # It sends: encode_with_length_prefix(payload, args.header_bytes, args.endian)
    # Payload is generated by iso8583.encode(..., spec) which adheres to 'spec'.
    # If 'spec' says 'ascii' length encoding for LVAR, it writes ASCII bytes. Endianness of ASCII digits is irrelevant.
    # BUT, if spec has 'binary' length fields (e.g. 2 bytes binary length), then endianness MATTERS.
    
    # default_ascii uses 'ascii' for length encoding of LVARs.
    # So LVAR length is "12" (bytes 0x31 0x32). Endianness doesn't apply to byte arrays of text.
    
    # So for ASCII spec, only the Frame Header (TCP) is affected by Endianness.
    pass
except Exception as e:
    print(e)
