# Copyright 2025 JAAB Tech SAS, Uruguay
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

*** Settings ***
Documentation     Cross-Rack Topology Validation
...               Verifies that messages flow from Rack A -> Mixer -> Rack B (simulated)
...               or simply Rack -> Mixer ingestion.
Resource          ../../resources/common.resource
Library           OperatingSystem
Suite Setup       Initialize Topology Suite    ${CURDIR}
Suite Teardown    Teardown Test Environment

*** Variables ***
${MIXER_PORT}     8090
${RACK_PORT}      9110
${WORK_DIR}       ${EMPTY}

*** Test Cases ***
Setup Infrastructure
    [Documentation]    Starts the Mixer and ensures it is healthy.
    Log    Starting Mixer...
    Generate Cluster Key   work_dir=${WORK_DIR}/mixer
    Start Mixer    config_file=${MIXER_CONFIG}    work_dir=${WORK_DIR}/mixer    alias=mixer
    Wait For Healthy    port=${MIXER_PORT}
    
    Check Log Contains    pattern=Mixer Control Plane listening
    Check Log Contains    pattern=Mixer is ready

Register Primary Rack (Rack A)
    [Documentation]    Starts Rack A in Cattle mode, verifies pending status, and adopts it.
    Log    Starting Rack A...
    Start Rack    config_file=${RACK_CONFIG}    work_dir=${WORK_DIR}/rack-a    mixer_home=${WORK_DIR}/mixer    alias=rack-a
    
    ${machine_id}=    Wait For Pending Rack    mixer_port=${MIXER_PORT}
    Set Suite Variable    ${RACK_A_ID}    ${machine_id}
    Log    Found Pending Rack with ID: ${RACK_A_ID}
    
    Check Stdout Contains    pattern=Starting FluxRig Rack    alias=rack-a

    Log    Adopting Rack A...
    Adopt Rack    mixer_port=${MIXER_PORT}    machine_id=${RACK_A_ID}    name=rack-a-adopted

    Verify Rack Status    mixer_port=${MIXER_PORT}    machine_id=${RACK_A_ID}    expected_status=active
    Log    Rack A is now ACTIVE.

Configure Topology
    [Documentation]    Imports the topology scenario to define roles and secondary racks.
    Import Scenario    mixer_port=${MIXER_PORT}    file_path=${SCENARIO_TOPOLOGY}

Register Secondary Rack (Rack B)
    [Documentation]    Starts Rack B and verifies it joins the cluster as Active (pre-defined).
    Log    Starting Rack B...
    Start Rack    config_file=${RACK_B_CONFIG}    work_dir=${WORK_DIR}/rack-b    mixer_home=${WORK_DIR}/mixer    alias=rack-b
    
    Wait For Rack Registration    mixer_port=${MIXER_PORT}    rack_name=rack-b
    
    ${status}=    Get Rack Status By Name    mixer_port=${MIXER_PORT}    rack_name=rack-b
    Log    Rack B Status is: ${status}
    
    run keyword if    '${status}' == 'pending'    Adopt Rack B Helper
    run keyword if    '${status}' != 'active' and '${status}' != 'pending'    Fail    Rack B is in bad status: ${status}
    
    # Verification
    ${status_final}=    Get Rack Status By Name    mixer_port=${MIXER_PORT}    rack_name=rack-b
    Should Be Equal    ${status_final}    active

Validate Functional Traffic (Phase 1)
    [Documentation]    Verifies that messages generated by Rack A reach Rack B (Blackhole).
    # Rack A (Bento Gen) -> Mixer -> Rack B (Blackhole)
    # Rack B logs "Received Message: phase1_test_..."
    
    # Restart Rack A to ensure it picks up the (dynamically assigned) Gear from topology
    Log    Restarting Rack A to pick up Gear...
    Stop Process    alias=rack-a
    # Re-start using same work_dir to preserve identity (keys/passport)
    Start Rack    config_file=${RACK_CONFIG}    work_dir=${WORK_DIR}/rack-a    mixer_home=${WORK_DIR}/mixer    alias=rack-a
    
    # Verify Rack A picked up the Gear (Check log file for gear start)
    Sleep    5s
    ${logs_a}=    Grep File    ${WORK_DIR}/rack-a/logs/fluxrig.log    gear started
    Should Not Be Empty    ${logs_a}    Rack A failed to start gears
    
    Log    Waiting for message flow...
    Sleep    5s
    
    # Rack B (Blackhole Bento Log) logs to stdout/stderr
    Check Stdout Contains    pattern=phase1_test    alias=rack-b

Validate Metrics
    [Documentation]    Verifies that Entity Stats are correctly reported for Racks and Gears.
    Log    Verifying Metrics for Rack A...
    Wait Until Keyword Succeeds    30x    1s    Verify Entity Metric Present    mixer_port=${MIXER_PORT}    entity_name=rack-a-adopted    metric_key=fluxrig.bus.publish_count
    
    Log    Verifying Metrics for Bento Gen...
    Wait Until Keyword Succeeds    30x    1s    Verify Entity Metric Present    mixer_port=${MIXER_PORT}    entity_name=bento-gen    metric_key=fluxrig.gear.messages_out_total

    Log    Verifying Metrics for Rack B...
    Wait Until Keyword Succeeds    30x    1s    Verify Entity Metric Present    mixer_port=${MIXER_PORT}    entity_name=rack-b    metric_key=fluxrig.bus.publish_count

Validate Telemetry Persistence (Phase 1)
    [Documentation]    Verifies that Telemetry data is persisted to Parquet files.
    Log    Waiting for telemetry flush...
    Sleep    10s
    
    Verify Telemetry Parquet Exists    work_dir=${WORK_DIR}/mixer
    
    # Verify we have plenty of logs (from Bento)
    # Check Stdout Contains    pattern=level=info    alias=rack-b

Report Statistics
    [Documentation]    Dumps registry and telemetry stats for analysis.
    Log Registry Contents    mixer_port=${MIXER_PORT}
    Log Telemetry Stats    work_dir=${WORK_DIR}/mixer

Validate Log Parity
    [Documentation]    Compares physical log file counts vs Parquet log counts.
    @{rack_dirs}=    Create List    ${WORK_DIR}/rack-a    ${WORK_DIR}/rack-b
    Verify Log Parity    mixer_dir=${WORK_DIR}/mixer    rack_dirs=${rack_dirs}



*** Keywords ***
Initialize Topology Suite
    [Arguments]    ${suite_path}
    Force Cleanup Environment
    ${wd}=    Setup Workspace    ${suite_path}    output_dir=${OUTPUT_DIR}
    Set Suite Variable    ${WORK_DIR}    ${wd}
    
    # Define Config Paths
    Set Suite Variable    ${MIXER_CONFIG}    ${suite_path}/configs/mixer/fluxrig-mixer.toml
    # Use Cattle Config (No Name) for this suite
    Set Suite Variable    ${RACK_CONFIG}     ${suite_path}/configs/rack/cattle.toml
    Set Suite Variable    ${RACK_B_CONFIG}   ${suite_path}/configs/rack/rack_b.toml
    # Scenario Path
    Set Suite Variable    ${SCENARIO_TOPOLOGY}    ${suite_path}/scenarios/topology.yaml

Adopt Rack B Helper
    ${mid_b}=    Wait For Pending Rack    mixer_port=${MIXER_PORT}
    Log    Adopting Pending Rack B: ${mid_b}
    Adopt Rack    mixer_port=${MIXER_PORT}    machine_id=${mid_b}    name=rack-b
