// Copyright (c) 2026 JAAB Tech SAS, Uruguay
// SPDX-License-Identifier: Apache-2.0

package commands

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/jaab-tech/fluxrig/pkg/gears"
	"github.com/jaab-tech/fluxrig/pkg/sdk"
)

// gearsDocCmd renders a gear's manifest as a Markdown reference section: an
// identity table, the declared ports, and the configuration fields derived from
// the config JSON Schema. This is the source that `make gear-docs` injects into
// each gear reference page between AUTOGEN markers, so the ports and config
// tables never drift from the code.
var gearsDocCmd = &cobra.Command{
	Use:   "doc [type]",
	Short: "Render a gear manifest as a Markdown reference section",
	Long: `Render the manifest for a gear type as Markdown (identity, ports, and
configuration fields from the config JSON Schema). With --all, prints a section
per gear. Consumed by 'make gear-docs' to keep the reference pages in sync with
the code.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		f := gears.NewFactory()
		all, _ := cmd.Flags().GetBool("all")
		out := cmd.OutOrStdout()

		// --write scans a docs directory and refreshes every AUTOGEN:manifest
		// block in place, keyed by the gear type in the marker.
		if docsDir, _ := cmd.Flags().GetString("write"); docsDir != "" {
			return injectDocs(f, docsDir, out)
		}

		if all {
			mans := f.Manifests()
			sort.Slice(mans, func(i, j int) bool { return mans[i].Type < mans[j].Type })
			for i, m := range mans {
				if i > 0 {
					_, _ = fmt.Fprintln(out)
				}
				_, _ = fmt.Fprint(out, renderManifestMarkdown(m))
			}
			return nil
		}
		if len(args) != 1 {
			return fmt.Errorf("provide a gear type, or --all (see 'fluxrig gears list')")
		}
		m, ok := f.Manifest(args[0])
		if !ok {
			return fmt.Errorf("unknown gear type %q (see 'fluxrig gears list')", args[0])
		}
		_, _ = fmt.Fprint(out, renderManifestMarkdown(m))
		return nil
	},
}

// autogenBlockRe matches one AUTOGEN:manifest block, capturing the gear type
// from the START marker so the injector can regenerate it from that gear's
// manifest. Go's RE2 has no backreferences, so the END marker matches any type;
// blocks are never nested and the non-greedy body stops at the nearest END.
var autogenBlockRe = regexp.MustCompile(`(?s)<!-- AUTOGEN:manifest:([a-z0-9_]+) START.*?<!-- AUTOGEN:manifest:[a-z0-9_]+ END -->\n?`)

// injectDocs walks docsDir, replaces every AUTOGEN:manifest block with a freshly
// rendered section for its gear type, and reports what changed. It never writes
// a file whose blocks are already current, so the target dir stays idempotent.
func injectDocs(f *gears.Factory, docsDir string, out io.Writer) error {
	var updated, unchanged int
	var unknown []string
	err := filepath.WalkDir(docsDir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".md") {
			return err
		}
		raw, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		if !autogenBlockRe.Match(raw) {
			return nil
		}
		next := autogenBlockRe.ReplaceAllFunc(raw, func(block []byte) []byte {
			gtype := string(autogenBlockRe.FindSubmatch(block)[1])
			m, ok := f.Manifest(gtype)
			if !ok {
				unknown = append(unknown, gtype+" ("+filepath.Base(path)+")")
				return block // leave an unknown type untouched
			}
			return []byte(renderManifestMarkdown(m))
		})
		if string(next) == string(raw) {
			unchanged++
			return nil
		}
		if werr := os.WriteFile(path, next, 0o644); werr != nil {
			return werr
		}
		updated++
		_, _ = fmt.Fprintf(out, "updated %s\n", path)
		return nil
	})
	if err != nil {
		return err
	}
	_, _ = fmt.Fprintf(out, "gear docs: %d updated, %d already current\n", updated, unchanged)
	if len(unknown) > 0 {
		return fmt.Errorf("unknown gear types in AUTOGEN markers: %s", strings.Join(unknown, ", "))
	}
	return nil
}

// renderManifestMarkdown turns a manifest into a Markdown section wrapped in
// AUTOGEN markers keyed by gear type, so the injector can find and replace the
// exact block.
func renderManifestMarkdown(m sdk.Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- AUTOGEN:manifest:%s START (generated by `fluxrig gears doc %s`; do not edit by hand) -->\n", m.Type, m.Type)

	// Identity.
	b.WriteString("| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| **Type** | `%s` |\n", m.Type)
	fmt.Fprintf(&b, "| **Category** | %s |\n", m.Category)
	fmt.Fprintf(&b, "| **Status** | %s |\n", m.Status)
	fmt.Fprintf(&b, "| **Terminus** | %s |\n", m.Terminus)
	if m.Summary != "" {
		fmt.Fprintf(&b, "\n%s\n", mdxText(m.Summary))
	}

	// Ports.
	if len(m.Ports) > 0 {
		b.WriteString("\n**Ports**\n\n")
		b.WriteString("| Port | Direction | Role | Summary |\n|---|---|---|---|\n")
		for _, p := range m.Ports {
			dir := string(p.Dir)
			if p.Dynamic {
				dir += " (dynamic)"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", p.Name, dir, cell(p.Role), cell(p.Summary))
		}
	}

	// Configuration (from the JSON Schema).
	if fields := parseSchemaFields(m.ConfigSchema); len(fields) > 0 {
		b.WriteString("\n**Configuration**\n\n")
		b.WriteString("| Field | Type | Required | Default | Description |\n|---|---|---|---|---|\n")
		for _, fld := range fields {
			req := ""
			if fld.required {
				req = "yes"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", fld.name, cell(fld.typ), req, cell(fld.def), cell(fld.desc))
		}
	} else if strings.TrimSpace(m.ConfigSchema) == "" {
		b.WriteString("\nThis gear takes no configuration.\n")
	}

	fmt.Fprintf(&b, "<!-- AUTOGEN:manifest:%s END -->\n", m.Type)
	return b.String()
}

type schemaField struct {
	name, typ, desc, def string
	required             bool
}

// parseSchemaFields extracts the top-level properties of a draft-07 config
// schema into a stable, sorted field list. Required fields are marked; enums are
// summarized into the type cell so a doc reader sees the allowed values.
func parseSchemaFields(schema string) []schemaField {
	if strings.TrimSpace(schema) == "" {
		return nil
	}
	var s struct {
		Properties map[string]struct {
			Type        any    `json:"type"`
			Description string `json:"description"`
			Enum        []any  `json:"enum"`
			Default     any    `json:"default"`
		} `json:"properties"`
		Required []string `json:"required"`
	}
	if err := json.Unmarshal([]byte(schema), &s); err != nil {
		return nil
	}
	req := make(map[string]bool, len(s.Required))
	for _, r := range s.Required {
		req[r] = true
	}
	out := make([]schemaField, 0, len(s.Properties))
	for name, p := range s.Properties {
		typ := schemaType(p.Type)
		if len(p.Enum) > 0 {
			vals := make([]string, 0, len(p.Enum))
			for _, e := range p.Enum {
				vals = append(vals, fmt.Sprintf("`%v`", e))
			}
			typ = "enum: " + strings.Join(vals, ", ")
		}
		def := ""
		if p.Default != nil {
			def = fmt.Sprintf("`%v`", p.Default)
		}
		out = append(out, schemaField{name: name, typ: typ, desc: p.Description, def: def, required: req[name]})
	}
	sort.Slice(out, func(i, j int) bool {
		// Required first, then alphabetical, so the important fields lead.
		if out[i].required != out[j].required {
			return out[i].required
		}
		return out[i].name < out[j].name
	})
	return out
}

// schemaType renders a JSON Schema "type" (a string or a list) for a doc cell.
func schemaType(t any) string {
	switch v := t.(type) {
	case string:
		return v
	case []any:
		parts := make([]string, 0, len(v))
		for _, e := range v {
			if s, ok := e.(string); ok {
				parts = append(parts, s)
			}
		}
		return strings.Join(parts, " or ")
	default:
		return ""
	}
}

// mdxJSXEscaper neutralizes the characters MDX would try to parse as JSX in a
// docs page (Docusaurus processes .md as MDX): `<` starts a tag, `{`/`}` an
// expression. Port names and field names are emitted inside backticks (inline
// code, already literal in MDX), so only free-text fields need this.
var mdxJSXEscaper = strings.NewReplacer("<", "&lt;", ">", "&gt;", "{", "&#123;", "}", "&#125;")

// mdxText makes a free-text string safe to drop into an MDX doc as prose.
func mdxText(s string) string {
	return mdxJSXEscaper.Replace(strings.TrimSpace(s))
}

// cell makes a free-text string safe for a Markdown table cell: MDX-escaped and
// with pipes escaped so they do not break the column. Empty renders as "-".
func cell(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "-"
	}
	return strings.ReplaceAll(mdxText(s), "|", "\\|")
}

func init() {
	gearsDocCmd.Flags().Bool("all", false, "Render a section for every gear type")
	gearsDocCmd.Flags().String("write", "", "Refresh every AUTOGEN:manifest block under this docs directory in place")
	gearsCmd.AddCommand(gearsDocCmd)
}
