// Copyright (c) 2026 JAAB Tech SAS, Uruguay
// SPDX-License-Identifier: Apache-2.0

package commands

import (
	"bytes"
	"crypto/ed25519"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"

	"github.com/spf13/cobra"

	"github.com/jaab-tech/fluxrig/pkg/pki"
	"github.com/jaab-tech/fluxrig/pkg/wasm/catalog"
)

var wasmCmd = &cobra.Command{
	Use:   "wasm",
	Short: "Manage WebAssembly Supply Chain Security",
}

var wasmImportCmd = &cobra.Command{
	Use:   "import [file.wasm]",
	Short: "Import a Wasm module to the Mixer catalog",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		allowUnsigned, _ := cmd.Flags().GetBool("allow-unsigned")
		filePath := args[0]

		f, err := os.Open(filePath)
		if err != nil {
			return err
		}
		defer func() { _ = f.Close() }()

		wasmBytes, err := io.ReadAll(f)
		if err != nil {
			return err
		}

		url := fmt.Sprintf("http://localhost:8090/api/v1/wasm/import?allow_unsigned=%t", allowUnsigned)
		req, err := http.NewRequest("POST", url, bytes.NewReader(wasmBytes))
		if err != nil {
			return err
		}
		req.Header.Set("Content-Type", "application/octet-stream")

		client := &http.Client{}
		resp, err := client.Do(req)
		if err != nil {
			return err
		}
		defer func() { _ = resp.Body.Close() }()

		if resp.StatusCode != http.StatusOK {
			body, _ := io.ReadAll(resp.Body)
			return fmt.Errorf("import failed: %s - %s", resp.Status, string(body))
		}

		var result map[string]interface{}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return err
		}

		fmt.Printf("Successfully imported Wasm module.\nHash: %s\nStatus: %s\n", result["hash"], result["status"])
		return nil
	},
}

var wasmSignCmd = &cobra.Command{
	Use:   "sign [file.wasm] [private_key.flux]",
	Short: "Embed a Vendor signature into a Wasm module",
	Args:  cobra.ExactArgs(2),
	RunE: func(cmd *cobra.Command, args []string) error {
		filePath := args[0]
		keyPath := args[1]

		// 1. Load the Wasm
		wasmBytes, err := os.ReadFile(filePath)
		if err != nil {
			return fmt.Errorf("failed to read wasm: %w", err)
		}

		// 2. Extract existing vendor signature if present
		_, stripped, errExt := catalog.ExtractCustomSection(wasmBytes, "fluxrig.signature")
		if errExt == nil {
			wasmBytes = stripped
		}

		// 3. Load Key
		env, err := pki.LoadStateEnvelope(keyPath)
		var privKey ed25519.PrivateKey
		if err != nil {
			// If not a state envelope, maybe a direct ed25519 private key?
			// We only officially support ClusterKey structure for vendor keys.
			clusterKey, errKey := pki.LoadClusterKey(keyPath)
			if errKey != nil {
				return fmt.Errorf("failed to load private key: %w", errKey)
			}
			privKey = clusterKey.Private
		} else {
			// Extracted from envelope? Envelopes don't contain private keys.
			// Assume it's a ClusterKey file.
			_ = env
			return fmt.Errorf("use a cluster.key generated by fluxrig pki init")
		}

		// 4. Sign
		hash := catalog.HashWasm(wasmBytes)
		sig := ed25519.Sign(privKey, hash)

		// 5. Append Custom Section
		signedWasm, err := catalog.AppendCustomSection(wasmBytes, "fluxrig.signature", sig)
		if err != nil {
			return fmt.Errorf("failed to append signature: %w", err)
		}

		if err := os.WriteFile(filePath, signedWasm, 0644); err != nil {
			return fmt.Errorf("failed to write signed wasm: %w", err)
		}

		fmt.Printf("Successfully signed %s with fluxrig.signature.\n", filePath)
		return nil
	},
}

var wasmListCmd = &cobra.Command{
	Use:   "list",
	Short: "List Wasm modules in the Mixer catalog",
	RunE: func(cmd *cobra.Command, args []string) error {
		resp, err := http.Get("http://localhost:8090/api/v1/wasm/catalog")
		if err != nil {
			return err
		}
		defer func() { _ = resp.Body.Close() }()

		if resp.StatusCode != http.StatusOK {
			return fmt.Errorf("failed to get catalog: %s", resp.Status)
		}

		var list []map[string]interface{}
		if err := json.NewDecoder(resp.Body).Decode(&list); err != nil {
			return err
		}

		for _, item := range list {
			fmt.Printf("- Hash: %s\n  Status: %s\n  Size: %.2f KB\n\n", item["hash"], item["status"], float64(item["size_bytes"].(float64))/1024.0)
		}
		return nil
	},
}

func init() {
	rootCmd.AddCommand(wasmCmd)
	wasmCmd.AddCommand(wasmImportCmd)
	wasmCmd.AddCommand(wasmSignCmd)
	wasmCmd.AddCommand(wasmListCmd)

	wasmImportCmd.Flags().Bool("allow-unsigned", false, "Allow import of Wasm modules without a trusted Vendor signature")
}
